#!/bin/bash

# TASK 1 - automated create users and groups from file
# Matt Revell - Operating Systems Concepts 2021
# This batch script automates user and group creation from a CSV file

#basename get file from uri

#count users created count++

# wget uri
# check if uri or local file? 
# if wget --spider http://google.com 2>/dev/null; then
#   echo "File exists"
# else
#   echo "File does not exist"
# fi

# use of log file and output also - make function to output and store in log


# Check if a filename was supplied as an arguement when running the script
# if not get a filename input
# underscore local vars?

function checkarguements () {
	local _filename=""
	echo 'Checking if filename supplied as arguement'
	# _filename=$1 assume this so can remove else ?
	if [ $# -ne 1 ]
	then
		echo 'No file arguement supplied'
		read -p "Input a filename or URI: " _filename
		echo "$_filename"
	else
		_filename=$1
		echo "$_filename"
	fi
}








function end () {
	echo 'Goodbye ...'
}

function title () {
	clear
	echo 'Titles'
}

function createusers () {
	# use IFS ; save and restore current/old IFS

	OLDIFS=$IFS
	IFS=";"
	
	
}

function main () {
	local filename=""		# create a local variable ...
	title
	
}

main
exit
