#!/bin/bash

# TASK 2 - backup a directory and copy it to a folder on a server address
# Matt Revell - Operating Systems Concepts 2021
# This batch script automates folder compression and copy to server for backup

# CODE ---------------------------------------------------------------------

# Check if there are were any arguements used when the script was executed
# If not then get an input from the user.

clear
echo " "
echo " **********************"
echo " Task 2 - Backup Script"
echo " **********************"
echo " "

if [ $# -ne 1 ]
	then
		echo "No directory specified"
		read -p "Please enter a directory to backup (hint - 'testdir') : " directory
	else
		directory=$1
fi

# Check if the directory exists. If not then exit the program.
if [ ! -d "$directory" ]
then
	echo "Directory does not exist"
	echo "Exiting ..."
	exit
fi

# Compress the directory to a tar file
filename="backup.tar.gz"
tar -czvf "$filename" "$directory"
echo " "
echo "The above files from $directory have been compressed into $filename"
echo " "

# Get the arguements for secure copy from the user (e.g. IP, DIR, PORT)
echo "Please enter the values for the destination server"

read -p "IP (10.25.100.33): " ipaddress
read -p "Target Dir (targetdir): " targetdir
read -p "Port (22): " port

# Copy the file to the server
scp -P $port "$filename" student@$ipaddress:"$targetdir"
echo " "
echo "The backup file has been copied"

exit

# CODE ENDS ---------------------------------------------------------------
